# Generated by Django 4.2.25 on 2025-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='number',
            field=models.IntegerField(),
        ),
    ]
