# Generated by Django 4.2.25 on 2025-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2_2_app', '0002_alter_buses_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busraces',
            name='fromTo',
            field=models.CharField(choices=[('1', 'Ярославль - Москва'), ('2', 'Москва - Ярославль'), ('3', 'Кострома - Ярославль'), ('4', 'Ярославль - Кострома'), ('5', 'Рыбинск - Ярославль'), ('6', 'Ярославль - Рыбинск')], max_length=1),
        ),
    ]
