# Generated by Django 5.2.6 on 2025-11-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('departure', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('day_of_week', models.CharField(max_length=15, verbose_name='День недели')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО пассажира')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order_status', models.CharField(choices=[('booked', 'Забронирован'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='booked', max_length=20, verbose_name='Статус заказа')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2_3_app.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2_3_app.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Заказ билета',
                'verbose_name_plural': 'Заказы билетов',
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
