# Generated by Django 5.2.6 on 2025-10-27 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип автобуса')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buses/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тип автобуса',
                'verbose_name_plural': 'Типы автобусов',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя оператора')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='operators/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='ФИО пассажира')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passengers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название дня')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер рейса')),
                ('departure', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
                ('arrival_time', models.TimeField(verbose_name='Время прибытия')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая цена')),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.bustype', verbose_name='Тип автобуса')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.operator', verbose_name='Оператор')),
                ('operating_days', models.ManyToManyField(to='tickets.weekday', verbose_name='Дни работы')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight', verbose_name='Рейс')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.operator', verbose_name='Оператор')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Заказ билета',
                'verbose_name_plural': 'Заказы билетов',
                'ordering': ['-order_date'],
            },
        ),
    ]
