# Generated by Django 5.2.6 on 2025-11-10 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('type', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('luxury', 'Люкс')], max_length=20, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Вместимость')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Госномер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buses/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passengers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('day_of_week', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
                ('arrival_time', models.TimeField(verbose_name='Время прибытия')),
                ('departure_city', models.CharField(max_length=50, verbose_name='Город отправления')),
                ('arrival_city', models.CharField(max_length=50, verbose_name='Город прибытия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3_app.bus', verbose_name='Автобус')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('seat_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер места')),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Файл билета')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3_app.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_3_app.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Заказ билета',
                'verbose_name_plural': 'Заказы билетов',
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
