# Generated by Django 5.2.6 on 2025-11-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Город отправления')),
                ('arrival_city', models.CharField(max_length=100, verbose_name='Город прибытия')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость билета')),
                ('available_seats', models.IntegerField(verbose_name='Количество свободных мест')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['departure_date'],
            },
        ),
    ]
